[workspace]
channels = ["conda-forge"]
name = "Beamline workflow"
platforms = ["linux-64"]

[dependencies]
prefect = "3.*"
python = "<3.14"
prefect-docker = "*"
tiled = ">=0.2.11"


[pypi-dependencies]
xas = { git = "https://github.com/NSLS2/qas-xas.git", rev = "0af3ff6" }
bluesky-tiled-plugins = ">=2.0.5"
